# Generated by Django 4.2.19 on 2025-02-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_tieritem_options_remove_tieritem_tier_list_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entrada do Diário', 'verbose_name_plural': 'Entradas do Diário'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-date'], 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AlterModelOptions(
            name='passwordstorage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Senha', 'verbose_name_plural': 'Senhas'},
        ),
        migrations.AlterModelOptions(
            name='tieritem',
            options={'ordering': ['tier', 'created_at'], 'verbose_name': 'Item da Tier List', 'verbose_name_plural': 'Itens da Tier List'},
        ),
        migrations.AlterModelOptions(
            name='tierlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tier List', 'verbose_name_plural': 'Tier Lists'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-last_activity'], 'verbose_name': 'Atividade do Usuário', 'verbose_name_plural': 'Atividades dos Usuários'},
        ),
        migrations.AddField(
            model_name='passwordstorage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tieritem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='tieritem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tierlist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='tieritem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tieritem',
            name='tier',
            field=models.CharField(choices=[('S', 'S - Excepcional'), ('A', 'A - Ótimo'), ('B', 'B - Bom'), ('C', 'C - Médio'), ('D', 'D - Ruim'), ('F', 'F - Péssimo')], max_length=1, verbose_name='Tier'),
        ),
        migrations.AlterField(
            model_name='tieritem',
            name='tierlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.tierlist'),
        ),
        migrations.AlterField(
            model_name='tierlist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='Endereço IP'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atividade'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='path',
            field=models.CharField(max_length=255, verbose_name='Caminho'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user_agent',
            field=models.TextField(verbose_name='User Agent'),
        ),
        migrations.DeleteModel(
            name='StudentGrade',
        ),
    ]
